# -*- coding: utf-8 -*-
"""Authored FM definitions (interfaces verified against DE1_100 source; CALC_VALIDATE
content reused from the accepted Two Variable Calc V1.3 doc). Pseudo kinds:
 'h' header line, 'p' plain sentence, 's' a./b. substep, 'b' bullet (auto '•  ')."""

FMDATA = {}

FMDATA['ZSMPL_FM_CUSTOM_INDEX'] = {
 'name':'ZSMPL_FM_CUSTOM_INDEX',
 'imports':[('IM_PRE_TEXT','CHAR10','Prefix text (optional)')],
 'changing':[('CH_INDEX1','/SMPL/STR_TT_RSNUM','Index column – table 1'),
             ('CH_INDEX2','/SMPL/STR_TT_RSNUM','Index column – table 2 (optional)'),
             ('CH_INDEX3','/SMPL/STR_TT_RSNUM','Index column – table 3 (optional)')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Numbers each row of a table sequentially (1, 2, 3 …) and optionally mirrors that numbering into up to two additional index columns so parallel tables stay in sync. An optional text prefix can be prepended to each generated row number.'),
  ('h','2. Input Parameters'),
  ('b','IM_PRE_TEXT – optional text placed in front of each generated row number.'),
  ('b','CH_INDEX1 – primary index column to number (changing).'),
  ('b','CH_INDEX2 / CH_INDEX3 – optional additional index columns kept in step with CH_INDEX1.'),
  ('h','3. Processing Logic'),
  ('s','a. If CH_INDEX2 is already populated and equals CH_INDEX1, exit immediately to avoid unnecessary re-processing.'),
  ('s','b. Loop over CH_INDEX1; for each row set the value to the current row number (sy-tabix), prefixed with IM_PRE_TEXT when one is supplied.'),
  ('s','c. Copy the completed CH_INDEX1 into CH_INDEX2 and CH_INDEX3 so every index column matches.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','No exceptions are defined.'),
  ('h','Dependencies:'),
  ('b','Table type /SMPL/STR_TT_RSNUM; no database reads or external FM calls.'),
  ('h','Assumptions:'),
  ('b','All supplied index columns have the same number of rows so they remain aligned.'),
 ]}

FMDATA['ZSMPL_FM_VALIDATE_FLOW'] = {
 'name':'ZSMPL_FM_VALIDATE_FLOW',
 'imports':[('IV_TIME','F','Elapsed time (optional)'),
            ('IV_VOL','F','Measured volume (optional)'),
            ('IV_FLW_MIN','F','Minimum acceptable flow rate'),
            ('IV_FLW_MAX','F','Maximum acceptable flow rate')],
 'exports':[('EX_FLOW','F','Calculated flow rate')],
 'exceptions':[('FLOW_OUT_OF_RANGE','Calculated flow rate outside allowed range')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Calculates a flow rate from a measured volume and elapsed time and validates it against a configured minimum/maximum window.'),
  ('h','2. Input Parameters'),
  ('b','IV_TIME – elapsed time for the measurement (optional until entered).'),
  ('b','IV_VOL – volume measured over that time (optional until entered).'),
  ('b','IV_FLW_MIN / IV_FLW_MAX – minimum and maximum acceptable flow rate.'),
  ('h','3. Processing Logic'),
  ('s','a. If either IV_TIME or IV_VOL has not yet been entered, exit quietly – there is nothing to validate.'),
  ('s','b. Calculate the flow rate as (IV_VOL × 60) ÷ IV_TIME, multiplying before dividing to preserve precision, and return it in EX_FLOW.'),
  ('s','c. If EX_FLOW is below IV_FLW_MIN or above IV_FLW_MAX, raise FLOW_OUT_OF_RANGE.'),
  ('h','Output'),
  ('b','EX_FLOW – calculated flow rate (volume per 60 time units).'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','FLOW_OUT_OF_RANGE – the calculated flow rate falls outside the configured min/max window.'),
  ('h','Dependencies:'),
  ('b','None – pure arithmetic, no tables or external FMs.'),
  ('h','Assumptions:'),
  ('b','Volume and time use consistent units; the flow rate is expressed per 60 time units (e.g. mL per minute when time is captured in seconds).'),
 ]}

FMDATA['ZSMPL_FM_GET_EXP_DATE'] = {
 'name':'ZSMPL_FM_GET_EXP_DATE',
 'imports':[('IV_ORDER','AUFNR','Order Number (optional)'),
            ('IV_PHASE','VORNR','Activity Number (optional)'),
            ('IV_DAYSADD','CHAR3','Number of days to add'),
            ('IV_SDATE','/SMPL/STR_DE_START_DATE','Start date (optional)')],
 'exports':[('EV_END_DATE','/SMPL/STR_DE_START_DATE','Calculated expiry date')],
 'exceptions':[('PAST_DATES_NOT_ALLOWED','Expiry date cannot be in the past')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Calculates an expiry date by adding a configured number of days to a start date, defaulting to the current date when none is supplied.'),
  ('h','2. Input Parameters'),
  ('b','IV_ORDER / IV_PHASE – process order and phase context (optional).'),
  ('b','IV_DAYSADD – number of days to add to the start date.'),
  ('b','IV_SDATE – start date (optional); when blank or zero the current system date is used.'),
  ('h','3. Processing Logic'),
  ('s','a. Determine the start date: if IV_SDATE is initial or zero, use the current date (sy-datum); otherwise use IV_SDATE.'),
  ('s','b. Add IV_DAYSADD days to the start date to produce EV_END_DATE.'),
  ('s','c. If the resulting EV_END_DATE is earlier than today, issue an error message and raise PAST_DATES_NOT_ALLOWED.'),
  ('h','Output'),
  ('b','EV_END_DATE – calculated expiry date.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','PAST_DATES_NOT_ALLOWED – the calculated expiry date is earlier than the current date.'),
  ('h','Dependencies:'),
  ('b','Data element /SMPL/STR_DE_START_DATE; no database reads.'),
  ('h','Assumptions:'),
  ('b','IV_DAYSADD holds a valid numeric day count and a future-dated expiry is expected.'),
 ]}

FMDATA['ZSMPL_FM_FLASK_NUMBER'] = {
 'name':'ZSMPL_FM_FLASK_NUMBER',
 'imports':[('IM_ORDER','AUFNR','Order Number'),
            ('IM_PRODUCT','MATNR','Material Number'),
            ('IM_ID1','CHAR30','Parameter table identifier 1'),
            ('IM_ID2','CHAR30','Parameter table identifier 2'),
            ('IM_NUM_TV','CHAR1','Number of transfer vessels'),
            ('IM_VIA_MIN','INT1','Minimum viability %'),
            ('IM_INDICATOR','BOOLE_D','Manual-entry indicator (optional)')],
 'exports':[('EX_FLASK','/SMPL/STR_TT_CHAR30','Flask numbers'),
            ('EX_VCD','/SMPL/STR_TT_ONE_DEC','Viable cell density per flask'),
            ('EX_VIABILITY','/SMPL/STR_TT_INT1','Viability % per flask'),
            ('EX_T_VES','/SMPL/STR_TT_CHAR3','Transfer vessel assignment per flask'),
            ('EX_TV','/SMPL/STR_TT_CHAR3','Transfer vessel list'),
            ('EX_AVG_VCD','/SMPL/STR_TT_ONE_DEC','Average VCD per transfer vessel'),
            ('EX_USED','/SMPL/STR_TT_CHAR30','Flask used indicator (YES/NO/Not Viable)'),
            ('EX_QTY_TO_ADD','/SMPL/STR_TT_ERFMG','Culture quantity to add'),
            ('EX_UOM','ZSMPL_TT_CHAR15','Unit of measure'),
            ('EX_NUM_REQ','/SMPL/STR_TT_CHAR30','Number of flasks required')],
 'exceptions':[('ITEM_NOT_FOUND','Parameter table item not found'),
               ('AVERAGE_VCD_OUTSIDE_RANGE','Average VCD outside configured range'),
               ('NOT_ENOUGH_FLASKS','Not enough viable flasks for the vessels'),
               ('FLASK_IS_NOT_VIABLE','Flask is not viable'),
               ('MANUAL_ENTRY_ONLY','Manual entry only')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Retrieves the latest cell-count flask data for the order, calculates the average VCD, validates it against the configured range, and assigns viable flasks across the requested number of transfer vessels – returning the culture quantity and number of flasks to add.'),
  ('h','2. Input Parameters'),
  ('b','IM_ORDER – process order whose flask data is read.'),
  ('b','IM_PRODUCT / IM_ID1 / IM_ID2 – material and parameter-table identifiers used to look up VCD ranges, weights and flask counts.'),
  ('b','IM_NUM_TV – number of transfer vessels to populate.'),
  ('b','IM_VIA_MIN – minimum viability % a flask must meet to be used.'),
  ('b','IM_INDICATOR – when set, signals manual mode.'),
  ('h','3. Processing Logic'),
  ('s','a. If IM_INDICATOR is set (manual mode), raise MANUAL_ENTRY_ONLY so the manual-update FM handles the change.'),
  ('s','b. Read flask details (ZTC_FLASK_DETAIL) for the order and keep only the rows for the most recent production day.'),
  ('s','c. Calculate the average VCD across flasks meeting IM_VIA_MIN; flasks below it are flagged "Not Viable" and excluded.'),
  ('s','d. Look up the VCD range for the product/IDs via ZSMPL_FM_PT_GET_RANGE; if the average falls outside every range, raise AVERAGE_VCD_OUTSIDE_RANGE.'),
  ('s','e. Read the culture weight to add and the number of flasks required for that range via ZSMPL_FM_PT_GET_SINGLE_VALUE; if the available viable flasks are fewer than required for the vessels, raise NOT_ENOUGH_FLASKS.'),
  ('s','f. Sort flasks by descending VCD and assign each to a transfer vessel in turn until the required count is met; remaining viable flasks are marked "NO" and non-viable ones "Not Viable".'),
  ('s','g. For each transfer vessel, calculate its average VCD and return the culture quantity, UoM and flask count.'),
  ('h','Output'),
  ('b','EX_FLASK / EX_VCD / EX_VIABILITY / EX_T_VES / EX_USED – per-flask number, VCD, viability, vessel assignment and used status.'),
  ('b','EX_TV / EX_AVG_VCD / EX_QTY_TO_ADD / EX_UOM / EX_NUM_REQ – per-vessel average VCD, culture quantity, UoM and flask count required.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','MANUAL_ENTRY_ONLY – called in manual mode; the manual-update FM is used instead.'),
  ('b','ITEM_NOT_FOUND – a required parameter-table value was not found.'),
  ('b','AVERAGE_VCD_OUTSIDE_RANGE – the average VCD does not fall within any configured range.'),
  ('b','NOT_ENOUGH_FLASKS – fewer viable flasks are available than the number required.'),
  ('b','FLASK_IS_NOT_VIABLE – a flask did not meet the minimum viability.'),
  ('h','Dependencies:'),
  ('b','Table ZTC_FLASK_DETAIL; FMs ZSMPL_FM_PT_GET_RANGE and ZSMPL_FM_PT_GET_SINGLE_VALUE; ALPHA conversion exits.'),
  ('h','Assumptions:'),
  ('b','The cell-count log is populated for the order; the parameter table holds VCD ranges, culture weights and flask counts per product.'),
 ]}

FMDATA['ZSMPL_FM_FLASK_NUMBER_UPD_TV'] = {
 'name':'ZSMPL_FM_FLASK_NUMBER_UPD_TV',
 'imports':[('IM_TV','/SMPL/STR_TT_CHAR3','Transfer vessel assignment per flask'),
            ('IM_VCD','/SMPL/STR_TT_ONE_DEC','Viable cell density per flask'),
            ('IM_USED','/SMPL/STR_TT_CHAR30','Flask used indicator'),
            ('IM_PRODUCT','MATNR','Material Number'),
            ('IM_ID1','CHAR30','Parameter table identifier 1'),
            ('IM_ID2','CHAR30','Parameter table identifier 2'),
            ('IM_IND','BOOLE_D','Recalculate indicator')],
 'exports':[('EX_TV','/SMPL/STR_TT_CHAR3','Transfer vessel list'),
            ('EX_AVG_VCD','/SMPL/STR_TT_ONE_DEC','Average VCD per transfer vessel'),
            ('EX_QTY_TO_ADD','/SMPL/STR_TT_ERFMG','Culture quantity to add'),
            ('EX_UOM','ZSMPL_TT_CHAR15','Unit of measure'),
            ('EX_NUM_REQ','/SMPL/STR_TT_CHAR30','Number of flasks required')],
 'exceptions':[('FLASK_IS_NOT_VIABLE','Flask is not viable'),
               ('ITEM_NOT_FOUND','Parameter table item not found'),
               ('AVERAGE_VCD_OUTSIDE_RANGE','Average VCD outside configured range'),
               ('INVALID_ENTRY','Invalid transfer vessel entry')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Recalculates the per-transfer-vessel average VCD, culture quantity and flask count after a manual reassignment of flasks to vessels.'),
  ('h','2. Input Parameters'),
  ('b','IM_TV / IM_VCD / IM_USED – the current per-flask vessel assignment, VCD and used status.'),
  ('b','IM_PRODUCT / IM_ID1 / IM_ID2 – material and parameter-table identifiers.'),
  ('b','IM_IND – when not set, the FM exits without recalculating.'),
  ('h','3. Processing Logic'),
  ('s','a. If IM_IND is not set, exit immediately.'),
  ('s','b. Build a working table of vessel/VCD/used rows and keep only flasks marked used = "YES".'),
  ('s','c. Sort by transfer vessel and, for each vessel group, total the VCD and divide by the flask count to get the average VCD.'),
  ('s','d. Look up the matching VCD range (ZSMPL_FM_PT_GET_RANGE) and read the culture weight and flask count for that range (ZSMPL_FM_PT_GET_SINGLE_VALUE); raise AVERAGE_VCD_OUTSIDE_RANGE or ITEM_NOT_FOUND on failure.'),
  ('s','e. Append the vessel, average VCD, culture quantity, UoM and required flask count to the export tables.'),
  ('h','Output'),
  ('b','EX_TV / EX_AVG_VCD / EX_QTY_TO_ADD / EX_UOM / EX_NUM_REQ – recalculated per-vessel results.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','AVERAGE_VCD_OUTSIDE_RANGE – the recalculated average VCD is outside every configured range.'),
  ('b','ITEM_NOT_FOUND – a required parameter-table value was not found.'),
  ('h','Dependencies:'),
  ('b','FMs ZSMPL_FM_PT_GET_RANGE and ZSMPL_FM_PT_GET_SINGLE_VALUE; ALPHA conversion exit.'),
  ('h','Assumptions:'),
  ('b','The flask-to-vessel assignment and used flags supplied by the table are consistent and ordered by flask.'),
 ]}

FMDATA['ZSMPL_FM_FLASK_NUMBER_MANUAL'] = {
 'name':'ZSMPL_FM_FLASK_NUMBER_MANUAL',
 'imports':[('IM_NUM_TV','CHAR1','Number of transfer vessels'),
            ('IM_FLASK','/SMPL/STR_TT_CHAR30','Flask numbers'),
            ('IM_TV','/SMPL/STR_TT_CHAR3','Transfer vessel assignment per flask'),
            ('IM_USED','/SMPL/STR_TT_CHAR30','Flask used indicator'),
            ('IM_FLASK_LINE','CHAR30','Edited flask number'),
            ('IM_TV_LINE','CHAR3','Edited transfer vessel value'),
            ('IM_USED_LINE','CHAR30','Edited used value')],
 'exports':[('EX_USED','/SMPL/STR_TT_CHAR30','Recalculated used indicator'),
            ('EX_IND','BOOLE_D','Recalculate indicator')],
 'exceptions':[('FLASK_IS_NOT_VIABLE','Flask is not viable'),
               ('ITEM_NOT_FOUND','Parameter table item not found'),
               ('AVERAGE_VCD_OUTSIDE_RANGE','Average VCD outside configured range'),
               ('INVALID_ENTRY','Invalid transfer vessel entry')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Validates a manual change to a flask’s transfer-vessel assignment, recalculates the used (YES/NO/Not Viable) status for every flask, and flags that the per-vessel averages must be refreshed.'),
  ('h','2. Input Parameters'),
  ('b','IM_NUM_TV – number of transfer vessels available.'),
  ('b','IM_FLASK / IM_TV / IM_USED – the current per-flask number, vessel assignment and used status.'),
  ('b','IM_FLASK_LINE / IM_TV_LINE / IM_USED_LINE – the flask, vessel value and used value of the edited row.'),
  ('h','3. Processing Logic'),
  ('s','a. Set the recalculate indicator EX_IND so the per-vessel averages are refreshed afterwards.'),
  ('s','b. If the edited vessel value is neither "NA"/"N/A" nor a value within 1..IM_NUM_TV, raise INVALID_ENTRY.'),
  ('s','c. If the edited flask is "Not Viable" but a vessel was assigned, raise FLASK_IS_NOT_VIABLE.'),
  ('s','d. Loop over the flasks: apply the edited vessel value to the edited flask and keep the others; derive each used status – "Not Viable" stays, a vessel of NA/N/A becomes "NO", otherwise "YES".'),
  ('s','e. Return the recalculated used indicators in EX_USED.'),
  ('h','Output'),
  ('b','EX_USED – recalculated per-flask used status.'),
  ('b','EX_IND – set so the transfer-vessel averages are recalculated.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','INVALID_ENTRY – the edited transfer vessel is outside the valid range.'),
  ('b','FLASK_IS_NOT_VIABLE – a non-viable flask was assigned to a vessel.'),
  ('h','Dependencies:'),
  ('b','Works on the Flask Info table values; no database reads.'),
  ('h','Assumptions:'),
  ('b','The flask, vessel and used tables are the same length and aligned by row.'),
 ]}

FMDATA['/SMPL/PPPI_FM_CALC_VALIDATE'] = {
 'name':'/SMPL/PPPI_FM_CALC_VALIDATE',
 'imports':[('IV_VAL1','CHAR30','Value 1 (input)'),
            ('IV_VAL2','CHAR30','Value 2 (input)'),
            ('IV_VAL3','CHAR30','Value 3 (input)'),
            ('IV_VAL1_DEF','CHAR30','Value 1 Default'),
            ('IV_TYPE1','CHAR1','Calculation Type 1'),
            ('IV_VAL2_DEF','CHAR30','Value 2 Default'),
            ('IV_TYPE2','I','Calculation Type 2'),
            ('IV_VAL3_DEF','CHAR30','Value 3 Default'),
            ('IV_RESULT_UOM','ERFME','Result Unit of Measure'),
            ('IV_MIN','F','Minimum Tolerance'),
            ('IV_MAX','F','Maximum Tolerance')],
 'exports':[('EV_VAL1','F','Value 1 (numeric)'),
            ('EV_VAL2','F','Value 2 (numeric)'),
            ('EV_VAL3','F','Value 3 (numeric)'),
            ('EV_RESULT','F','Calculation Result'),
            ('EV_RESULT_OUT','CHAR30','Calculation Result (formatted)')],
 'exceptions':[('INPUT_NOT_NUMERIC','Input is not numeric'),
               ('SIGNIFICANT_FIGURE_ISSUE','Significant figure issue'),
               ('VALUE_CHANGED','Value changed from default'),
               ('VALUE_BELOW_MIN','Result below minimum tolerance'),
               ('VALUE_ABOVE_MAX','Result above maximum tolerance'),
               ('UNEXPECTED_ERROR','Unexpected error')],
 'pseudo':[
  ('h','1. Convert Inputs to Float'),
  ('s','a. For each provided character input (IV_VAL1, IV_VAL2, IV_VAL3), call /SMPL/PPPI_FM_INPUT_VALUE to convert it to a float. If the conversion fails the value defaults to 0 (the INPUT_NOT_NUMERIC / SIGNIFICANT_FIGURE_ISSUE handling is present but its RAISE is commented out in the current source).'),
  ('h','2. Apply Defaults'),
  ('s','a. For each value, use the converted input when supplied; otherwise fall back to the corresponding default (IV_VAL1_DEF / IV_VAL2_DEF / IV_VAL3_DEF).'),
  ('h','3. Execute the Calculation'),
  ('s','a. Call /SMPL/PPPI_FM_CALC_EXECUTE with the resolved values, the calculation types (IV_TYPE1 / IV_TYPE2) and the result UoM (IV_RESULT_UOM) to produce the numeric result EV_RESULT.'),
  ('s','b. Call /SMPL/PPPI_FM_OUTPUT_VALUE to format EV_RESULT into the display string EV_RESULT_OUT; return the per-value floats in EV_VAL1 / EV_VAL2 / EV_VAL3.'),
  ('h','4. Tolerance Validation'),
  ('s','a. If IV_MIN is supplied and EV_RESULT is below it, raise VALUE_BELOW_MIN ("Result below tolerance value, sign to continue").'),
  ('s','b. If IV_MAX is supplied and EV_RESULT is above it, raise VALUE_ABOVE_MAX ("Result above tolerance value, sign to continue").'),
  ('h','Additional Notes'),
  ('p','Validator wired to the Calc Table input column; converts and validates the operator’s entry, runs the calculation and enforces the configured min/max tolerances on the result.'),
  ('p','Calls /SMPL/PPPI_FM_INPUT_VALUE (numeric conversion), /SMPL/PPPI_FM_CALC_EXECUTE (calculation) and /SMPL/PPPI_FM_OUTPUT_VALUE (formatting). VALUE_CHANGED, INPUT_NOT_NUMERIC, SIGNIFICANT_FIGURE_ISSUE and UNEXPECTED_ERROR are declared in the interface but their RAISE statements are commented out in the current source.'),
 ]}

FMDATA['/SMPL/PPPI_FM_SET_LINE_IDX'] = {
 'name':'/SMPL/PPPI_FM_SET_LINE_IDX',
 'exports':[('ET_INDEX_T1','/SMPL/STR_TT_VORNR','Numbered index – copy 1'),
            ('ET_INDEX_T2','/SMPL/STR_TT_VORNR','Numbered index – copy 2')],
 'changing':[('CT_INDEX','/SMPL/STR_TT_VORNR','Table line index column')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Numbers each row of a table sequentially (1, 2, 3 …) and returns two copies of the numbered column for XSteps that drive more than one table from the same index.'),
  ('h','2. Parameters'),
  ('b','CT_INDEX – table line index column to number (changing).'),
  ('b','ET_INDEX_T1 / ET_INDEX_T2 – copies of the numbered column for additional tables.'),
  ('h','3. Processing Logic'),
  ('s','a. Loop over CT_INDEX; set each row to its current row number (sy-tabix) and left-justify the value.'),
  ('s','b. Copy the numbered CT_INDEX into ET_INDEX_T1 and ET_INDEX_T2.'),
  ('h','Output'),
  ('b','CT_INDEX (changing) plus ET_INDEX_T1 / ET_INDEX_T2 – the sequential row numbers.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','No exceptions are defined.'),
  ('h','Dependencies:'),
  ('b','Table type /SMPL/STR_TT_VORNR; no database reads.'),
  ('h','Assumptions:'),
  ('b','The index column has one row per table row to be numbered.'),
 ]}

FMDATA['ZSMPL_FM_RANGE_YES_NO'] = {
 'name':'ZSMPL_FM_RANGE_YES_NO',
 'imports':[('IM_NUM','F','Value to test'),
            ('IM_MIN','F','Minimum bound (optional)'),
            ('IM_MAX','F','Maximum bound (optional)')],
 'exports':[('EX_RESULT','CHAR10','Result (Yes/No)')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Returns "Yes" when a value falls within the supplied bound(s), otherwise "No". Used to drive a Yes/No column from a numeric reading and its configured limits.'),
  ('h','2. Input Parameters'),
  ('b','IM_NUM – the value being tested.'),
  ('b','IM_MIN / IM_MAX – minimum and/or maximum bound (either is optional).'),
  ('h','3. Processing Logic'),
  ('s','a. Default the result to "No".'),
  ('s','b. If both IM_MIN and IM_MAX are supplied, return "Yes" when IM_NUM is strictly between them.'),
  ('s','c. If only IM_MIN is supplied, return "Yes" when IM_NUM is greater than it; if only IM_MAX, return "Yes" when IM_NUM is less than it.'),
  ('s','d. If neither bound is supplied, the result stays "No".'),
  ('h','Output'),
  ('b','EX_RESULT – "Yes" or "No".'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','No exceptions are defined.'),
  ('h','Dependencies:'),
  ('b','None – pure comparison logic.'),
  ('h','Assumptions:'),
  ('b','Bounds are supplied as floats; a bound left initial (zero) is treated as not configured.'),
 ]}

_GMI_EXPORTS=[('EV_MAT_DESC','MAKTX','Material Description'),
              ('EV_BATCH','CHARG','Batch'),
              ('EV_BOM_QUANTITY','ERFMG','BOM Quantity'),
              ('EV_ISSUED_QUANTITY','ERFMG','Issued Quantity'),
              ('EV_UOM','ERFME','Unit of Measure'),
              ('EV_SERNR','SERNR','Serial Number'),
              ('EV_CHAR_EXP_DT','CHAR10','Expiry Date (formatted)'),
              ('EV_EXP_DT','ETDATE','Expiry Date'),
              ('EV_BATCHNO','CHARG_D','Batch Number')]

FMDATA['/SMPL/PPPI_FM_GET_MAT_ITEMS'] = {
 'name':'/SMPL/PPPI_FM_GET_MAT_ITEMS',
 'imports':[('I_ORDER','AUFNR','Order Number'),
            ('I_PHASE','VORNR','Activity Number (optional)'),
            ('I_MATERIAL','MATNR','Material Number (optional)'),
            ('I_BATCH','CHARG_D','Batch Number (optional)'),
            ('I_COUNT','INT3','Record count (optional)'),
            ('I_FLAG','CHAR1','Formatted-date flag (optional)')],
 'exports':_GMI_EXPORTS,
 'exceptions':[('TOO_MANY_RECORDS','Too many records returned')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Reads the process-order BOM components and returns each component’s description, batch, BOM/issued quantity, unit of measure and expiry date – used to populate and validate the Materials table.'),
  ('h','2. Input Parameters'),
  ('b','I_ORDER – process order whose components are read.'),
  ('b','I_PHASE / I_BATCH – optional filters for activity and batch.'),
  ('b','I_MATERIAL / I_COUNT – optional material and record-count context.'),
  ('b','I_FLAG – when "X", the expiry date is returned as a formatted string.'),
  ('h','3. Processing Logic'),
  ('s','a. If the component buffer is empty, call BAPI_PROCORD_GET_DETAIL for I_ORDER to read the order components.'),
  ('s','b. Filter the components by phase (I_PHASE) and batch (I_BATCH) when supplied.'),
  ('s','c. For each component, read the batch expiry (VFDAT from MCH1); when I_FLAG = "X" return it formatted in EV_CHAR_EXP_DT, otherwise in EV_EXP_DT.'),
  ('s','d. Return the material description, batch, BOM quantity, issued (withdrawn) quantity and UoM; default the quantities to 1 when the entry quantity is blank.'),
  ('h','Output'),
  ('b','EV_MAT_DESC / EV_BATCH / EV_BATCHNO – component description and batch.'),
  ('b','EV_BOM_QUANTITY / EV_ISSUED_QUANTITY / EV_UOM – BOM and issued quantity with unit.'),
  ('b','EV_EXP_DT / EV_CHAR_EXP_DT – batch expiry date (raw or formatted).'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','TOO_MANY_RECORDS – declared in the interface for multiple-match handling.'),
  ('h','Dependencies:'),
  ('b','BAPI_PROCORD_GET_DETAIL; tables MCH1 (expiry) and MSEG (material document); GET_SERNOS_OF_DOCUMENT for serial numbers.'),
  ('h','Assumptions:'),
  ('b','The order has BOM components; batch expiry is maintained in MCH1.'),
 ]}

FMDATA['ZSMPL_FM_GET_MAT_ITEMS_EBR'] = {
 'name':'ZSMPL_FM_GET_MAT_ITEMS_EBR',
 'imports':[('I_ORDER','AUFNR','Order Number (optional)'),
            ('I_PHASE','VORNR','Activity Number (optional)'),
            ('I_MATERIAL','MATNR','Material Number (optional)'),
            ('I_BATCH','CHARG_D','Batch Number (optional)'),
            ('I_COUNT','INT3','Record count (optional)'),
            ('I_FLAG','CHAR1','Formatted-date flag (optional)')],
 'exports':_GMI_EXPORTS,
 'exceptions':[('TOO_MANY_RECORDS','Too many records returned')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','EBR (Electronic Batch Record) variant of the material-items reader: returns each BOM component’s description, batch, BOM/issued quantity, UoM and expiry for the Materials table, reading the order components asynchronously when running in the EBR context.'),
  ('h','2. Input Parameters'),
  ('b','I_ORDER – process order whose components are read (optional).'),
  ('b','I_PHASE / I_BATCH – optional filters for activity and batch.'),
  ('b','I_MATERIAL / I_COUNT – optional material and record-count context.'),
  ('b','I_FLAG – when "X", the expiry date is returned as a formatted string.'),
  ('h','3. Processing Logic'),
  ('s','a. If the component buffer is empty and the EBR websocket function is active (SMPL_EBR), call BAPI_PROCORD_GET_DETAIL via an asynchronous RFC task; otherwise call it synchronously.'),
  ('s','b. Filter the buffered components by phase (I_PHASE) and batch (I_BATCH) when supplied.'),
  ('s','c. For each component, read the batch expiry (VFDAT from MCH1); when I_FLAG = "X" return it formatted in EV_CHAR_EXP_DT, otherwise in EV_EXP_DT.'),
  ('s','d. Return the material description, batch, BOM quantity, issued (withdrawn) quantity and UoM; default the quantities to 1 when the entry quantity is blank.'),
  ('h','Output'),
  ('b','EV_MAT_DESC / EV_BATCH / EV_BATCHNO – component description and batch.'),
  ('b','EV_BOM_QUANTITY / EV_ISSUED_QUANTITY / EV_UOM – BOM and issued quantity with unit.'),
  ('b','EV_EXP_DT / EV_CHAR_EXP_DT – batch expiry date (raw or formatted).'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','TOO_MANY_RECORDS – declared in the interface for multiple-match handling.'),
  ('h','Dependencies:'),
  ('b','BAPI_PROCORD_GET_DETAIL (async RFC in EBR mode via /smpl/ebr_cl_apc_ws); table MCH1 for batch expiry.'),
  ('h','Assumptions:'),
  ('b','The order has BOM components; in EBR mode the component buffer is populated by the asynchronous task before the table is filled.'),
 ]}

FMDATA['ZSMPL_FM_GET_FLASKS'] = {
 'name':'ZSMPL_FM_GET_FLASKS',
 'imports':[('IV_AUFNR','AUFNR','Order Number'),
            ('IV_MIN','ERFMG','Minimum VCD (optional)')],
 'exports':[('ET_FL_ID','/SMPL/STR_TT_CHAR30','Flask number'),
            ('ET_CU_VOL','/SMPL/STR_TT_ERFMG','Flask / culture quantity'),
            ('ET_VCD','/SMPL/STR_TT_ERFMG','Viable cell density'),
            ('ET_VIS','/SMPL/STR_TT_CHAR30','Viability %'),
            ('ET_CU_UOM','/SMPL/STR_TT_CHAR30','Quantity unit of measure'),
            ('ET_USED','/SMPL/STR_TT_CHAR30','Used indicator (Yes/No)')],
 'exceptions':[('FLASK_NOT_FOUND','No flask records found for the order')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Reads the most recent cell-count flask data for an order and returns each flask’s details, flagging whether the flask is usable based on a minimum VCD.'),
  ('h','2. Input Parameters'),
  ('b','IV_AUFNR – process order whose flask data is read.'),
  ('b','IV_MIN – minimum VCD a flask must reach to be marked as usable.'),
  ('h','3. Processing Logic'),
  ('s','a. Read the latest production day (MAX prod_day) from ZTC_FLASK_DETAIL for IV_AUFNR; if none exists, raise FLASK_NOT_FOUND.'),
  ('s','b. Select all flask rows for that order and production day; raise FLASK_NOT_FOUND if none are returned.'),
  ('s','c. For each flask, output the flask number, quantity, VCD, viability % and unit of measure.'),
  ('s','d. Mark ET_USED "No" when the flask’s VCD is below IV_MIN, otherwise "Yes".'),
  ('h','Output'),
  ('b','ET_FL_ID / ET_CU_VOL / ET_VCD / ET_VIS / ET_CU_UOM – per-flask number, quantity, VCD, viability and UoM.'),
  ('b','ET_USED – per-flask usable indicator (Yes/No).'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','FLASK_NOT_FOUND – no flask data exists for the order / latest production day.'),
  ('h','Dependencies:'),
  ('b','Table ZTC_FLASK_DETAIL.'),
  ('h','Assumptions:'),
  ('b','The cell-count log is populated for the order; the latest production day holds the flasks to evaluate.'),
 ]}

FMDATA['ZSMPL_FM_VALIDATE_QUANTITY'] = {
 'name':'ZSMPL_FM_VALIDATE_QUANTITY',
 'imports':[('IM_QTY_NUM','ERFMG','Quantity (numeric, optional)'),
            ('IM_QTY_CHAR','CHAR30','Quantity (character, optional)'),
            ('IM_FLAG','BOOLEAN','Exact-match flag'),
            ('IM_TARGET','ERFMG','Target value (optional)'),
            ('IM_MIN','ERFMG','Minimum tolerance (optional)'),
            ('IM_MAX','ERFMG','Maximum tolerance (optional)')],
 'exceptions':[('VALUE_OUTSIDE_TOLERANCE','Value outside tolerance'),
               ('TARGET_VAL_NOT_FOUND','Target value not provided')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Validates an entered quantity either against an exact target value or within a configured minimum/maximum range, depending on a flag.'),
  ('h','2. Input Parameters'),
  ('b','IM_QTY_NUM / IM_QTY_CHAR – the entered quantity as a number or as text.'),
  ('b','IM_FLAG – when set, validate against an exact target; otherwise validate against a range.'),
  ('b','IM_TARGET – exact target value (exact-match mode).'),
  ('b','IM_MIN / IM_MAX – minimum and maximum tolerance (range mode).'),
  ('h','3. Processing Logic'),
  ('s','a. Resolve the actual quantity: prefer IM_QTY_NUM, otherwise convert IM_QTY_CHAR to numeric – raise VALUE_OUTSIDE_TOLERANCE if it is not a number.'),
  ('s','b. Exact-value mode (IM_FLAG set): raise TARGET_VAL_NOT_FOUND when no target is supplied, then raise VALUE_OUTSIDE_TOLERANCE when the quantity does not equal IM_TARGET.'),
  ('s','c. Range mode (IM_FLAG not set): raise VALUE_OUTSIDE_TOLERANCE when the quantity is below IM_MIN or above IM_MAX.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','VALUE_OUTSIDE_TOLERANCE – the quantity is non-numeric, not equal to the target, or outside the range.'),
  ('b','TARGET_VAL_NOT_FOUND – exact-match mode was requested but no target value was supplied.'),
  ('h','Dependencies:'),
  ('b','None – numeric comparison only.'),
  ('h','Assumptions:'),
  ('b','The appropriate target or min/max tolerances are configured for the column being validated.'),
 ]}

FMDATA['/SMPL/PPPI_FM_INPUT_VALUE'] = {
 'name':'/SMPL/PPPI_FM_INPUT_VALUE',
 'imports':[('IV_VALUE','TEXT30','Entered value (number and optional UoM)'),
            ('IV_SIG_FIGS','I','Significant figures (optional)'),
            ('IV_DEC_MAX','I','Maximum decimals (optional)')],
 'exports':[('EV_VALUE','F','Numeric value'),
            ('EV_UOM','ERFME','Unit of measure')],
 'exceptions':[('INPUT_NOT_NUMERIC','Entered value is not numeric'),
               ('SIGNIFICANT_FIGURE_ISSUE','Incorrect significant figures'),
               ('MAXIMUM_DECIMALS_EXCEEDED','Too many decimals entered')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Converts an operator’s text entry from a basic XStep field into a float value (with its unit of measure), enforcing the configured significant-figure and decimal limits.'),
  ('h','2. Input Parameters'),
  ('b','IV_VALUE – the entered text, expected as "number UoM".'),
  ('b','IV_SIG_FIGS / IV_DEC_MAX – optional significant-figure and maximum-decimal limits.'),
  ('h','3. Processing Logic'),
  ('s','a. Split IV_VALUE at the first space into the numeric portion and the unit of measure (EV_UOM) and convert the numeric portion to a float; raise INPUT_NOT_NUMERIC if it is not numeric.'),
  ('s','b. Call /SMPL/PPPI_FM_ROUND_INPUT with IV_SIG_FIGS / IV_DEC_MAX to round the value; raise SIGNIFICANT_FIGURE_ISSUE or MAXIMUM_DECIMALS_EXCEEDED on failure.'),
  ('s','c. Return the rounded float in EV_VALUE.'),
  ('h','Output'),
  ('b','EV_VALUE – the numeric value.'),
  ('b','EV_UOM – the unit of measure parsed from the entry.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','INPUT_NOT_NUMERIC / SIGNIFICANT_FIGURE_ISSUE / MAXIMUM_DECIMALS_EXCEEDED – invalid numeric input, wrong significant figures, or too many decimals.'),
  ('h','Dependencies:'),
  ('b','/SMPL/PPPI_FM_ROUND_INPUT for rounding and figure/decimal checks.'),
  ('h','Assumptions:'),
  ('b','The value is entered as a number optionally followed by a unit of measure.'),
 ]}

FMDATA['/SMPL/PPPI_FM_CALC_SETUP'] = {
 'name':'/SMPL/PPPI_FM_CALC_SETUP',
 'imports':[('IV_VAL1','F','Value 1'),
            ('IV_TYPE1','CHAR1','Operation 1'),
            ('IV_VAL2','F','Value 2 (optional)'),
            ('IV_TYPE2','I','Operation 2 (optional)'),
            ('IV_VAL3','F','Value 3 (optional)'),
            ('IV_RESULT_UOM','ERFME','Result Unit of Measure (optional)')],
 'exports':[('EV_RESULT','F','Calculation result'),
            ('EV_RESULT_OUT','TEXT30','Result (formatted)'),
            ('ET_VAL1','/SMPL/STR_TT_FLOAT','Value 1 (table)'),
            ('ET_VAL2','/SMPL/STR_TT_FLOAT','Value 2 (table)'),
            ('ET_VAL3','/SMPL/STR_TT_FLOAT','Value 3 (table)'),
            ('ET_VAL1_OUT','/SMPL/STR_TT_SHORT_TEXT','Value 1 (formatted)'),
            ('ET_VAL2_OUT','/SMPL/STR_TT_SHORT_TEXT','Value 2 (formatted)'),
            ('ET_VAL3_OUT','/SMPL/STR_TT_SHORT_TEXT','Value 3 (formatted)'),
            ('ET_VAL1_IN','/SMPL/STR_TT_SHORT_TEXT','Value 1 (input display)'),
            ('ET_VAL2_IN','/SMPL/STR_TT_SHORT_TEXT','Value 2 (input display)'),
            ('ET_VAL3_IN','/SMPL/STR_TT_SHORT_TEXT','Value 3 (input display)')],
 'exceptions':[('INPUT_NOT_NUMERIC','Input is not numeric'),
               ('SIGNIFICANT_FIGURE_ISSUE','Significant figure issue'),
               ('UNEXPECTED_ERROR','Unexpected error')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Prepares the calculation table for a multi-variable XStep: runs the configured calculation and returns the result together with each individual value formatted for display.'),
  ('h','2. Input Parameters'),
  ('b','IV_VAL1 / IV_VAL2 / IV_VAL3 – the values to calculate with (value 2 and 3 optional).'),
  ('b','IV_TYPE1 / IV_TYPE2 – the mathematical operations to apply.'),
  ('b','IV_RESULT_UOM – unit of measure for the formatted result.'),
  ('h','3. Processing Logic'),
  ('s','a. Place IV_VAL1 (and IV_VAL2 / IV_VAL3 when supplied) into the per-value tables ET_VAL1/2/3.'),
  ('s','b. Call /SMPL/PPPI_FM_CALC_EXECUTE with the values, operations and result UoM to produce EV_RESULT.'),
  ('s','c. Call /SMPL/PPPI_FM_OUTPUT_VALUE to format EV_RESULT into EV_RESULT_OUT.'),
  ('s','d. For each supplied value, call /SMPL/PPPI_FM_OUTPUT_VALUE to build its display string (ET_VALn_OUT / ET_VALn_IN); default to "0.000" when a value is not supplied.'),
  ('h','Output'),
  ('b','EV_RESULT / EV_RESULT_OUT – numeric and formatted calculation result.'),
  ('b','ET_VAL1/2/3 – the per-value numeric tables; ET_VALn_OUT / ET_VALn_IN – the formatted display values.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','INPUT_NOT_NUMERIC / SIGNIFICANT_FIGURE_ISSUE / UNEXPECTED_ERROR – declared in the interface for conversion and calculation failures.'),
  ('h','Dependencies:'),
  ('b','/SMPL/PPPI_FM_CALC_EXECUTE (calculation) and /SMPL/PPPI_FM_OUTPUT_VALUE (formatting).'),
  ('h','Assumptions:'),
  ('b','The supplied operations are valid and the values are already numeric floats.'),
 ]}

FMDATA['/SMPL/PPPI_FM_OUTPUT_VALUE'] = {
 'name':'/SMPL/PPPI_FM_OUTPUT_VALUE',
 'imports':[('IV_VALUE','F','Value to format'),
            ('IV_UOM','ERFME','Unit of measure (optional)'),
            ('IV_SIG_FIG','I','Significant figures (default 5)'),
            ('IV_DEC_MAX','I','Maximum decimals (optional)'),
            ('IV_PRESERVE_FIGS','BOOLE_D','Preserve entered figures (optional)'),
            ('IV_ROUND_BEFORE_DEC','BOOLE_D','Round before decimals (optional)')],
 'exports':[('EV_VALUE','F','Numeric value'),
            ('EV_OUTPUT','TEXT30','Formatted output value')],
 'exceptions':[('UOM_DOESNT_EXIT','Unit of measure does not exist'),
               ('MAXIMUM_DECIMALS_EXCEEDED','Too many decimals')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Formats a float value into a display string with the configured significant figures and unit of measure for output on an XStep.'),
  ('h','2. Input Parameters'),
  ('b','IV_VALUE – the float value to format.'),
  ('b','IV_UOM – unit of measure appended to the output (optional).'),
  ('b','IV_SIG_FIG – significant figures to display (default 5); IV_DEC_MAX – optional decimal cap.'),
  ('b','IV_PRESERVE_FIGS / IV_ROUND_BEFORE_DEC – control figure preservation and rounding behaviour.'),
  ('h','3. Processing Logic'),
  ('s','a. Load the unit-of-measure data for IV_UOM (from buffer or T006 / T006A); raise UOM_DOESNT_EXIT if the UoM is invalid.'),
  ('s','b. Determine the significant figures to use – preserving the entered figures when IV_PRESERVE_FIGS is set, otherwise IV_SIG_FIG.'),
  ('s','c. Build the output string at the required precision and append the unit-of-measure text.'),
  ('s','d. When IV_DEC_MAX is supplied, re-round to that many decimals; raise MAXIMUM_DECIMALS_EXCEEDED if rounding would change the value.'),
  ('h','Output'),
  ('b','EV_VALUE – the (possibly rounded) numeric value.'),
  ('b','EV_OUTPUT – the formatted display string including the UoM.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','UOM_DOESNT_EXIT – the supplied unit of measure could not be found (note: spelled as in the source).'),
  ('b','MAXIMUM_DECIMALS_EXCEEDED – the value cannot be represented within the maximum decimals.'),
  ('h','Dependencies:'),
  ('b','Tables T006 / T006A for unit-of-measure text.'),
  ('h','Assumptions:'),
  ('b','The unit of measure, when supplied, is maintained in the UoM tables.'),
 ]}

FMDATA['/SMPL/PPPI_FM_SET_FLOAT_VALUE'] = {
 'name':'/SMPL/PPPI_FM_SET_FLOAT_VALUE',
 'imports':[('IV_VAL','F','Input float value')],
 'exports':[('EV_VAL','F','Output float value')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Pass-through helper that returns the supplied float value unchanged – used to move a float into an output field.'),
  ('h','2. Input Parameters'),
  ('b','IV_VAL – the input float value.'),
  ('h','3. Processing Logic'),
  ('s','a. Assign IV_VAL to EV_VAL.'),
  ('h','Output'),
  ('b','EV_VAL – the float value, unchanged.'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','No exceptions are defined.'),
  ('h','Dependencies:'),
  ('b','None.'),
  ('h','Assumptions:'),
  ('b','A direct float-to-float assignment is the intended behaviour.'),
 ]}



FMDATA['/SMPL/PPPI_FM_CALC_EXECUTE'] = {
 'name':'/SMPL/PPPI_FM_CALC_EXECUTE',
 'imports':[('IV_VAL1','F','Value 1'),
            ('IV_TYPE1','CHAR1','Operation 1 (+, -, *, /, abs-)'),
            ('IV_VAL2','F','Value 2'),
            ('IV_TYPE2','I','Operation 2 (optional)'),
            ('IV_VAL3','F','Value 3 (optional)'),
            ('IV_RESULT_UOM','ERFME','Result Unit of Measure (optional)')],
 'exports':[('EV_RESULT','F','Calculation result'),
            ('EV_RESULT_OUT','CHAR30','Result (formatted)')],
 'pseudo':[
  ('h','1. Purpose'),
  ('p','Generic calculation engine. Applies an arithmetic operation to two values (and optionally a '
   'second operation with a third value) and returns the numeric and formatted result. For Fill Volume '
   'Calculation it performs the subtraction Planned Final Volume − Seed Volume.'),
  ('h','2. Input Parameters'),
  ('b','IV_VAL1 / IV_VAL2 / IV_VAL3 – the values to calculate with (value 3 optional).'),
  ('b','IV_TYPE1 / IV_TYPE2 – the operation codes (plus, minus, multiply, divide, absolute-difference).'),
  ('b','IV_RESULT_UOM – unit of measure for the formatted result.'),
  ('h','3. Processing Logic'),
  ('s','a. If IV_VAL1 > 0, apply IV_TYPE1 to IV_VAL1 and IV_VAL2 to produce EV_RESULT. For Fill Volume '
   'Calculation IV_TYPE1 is "minus", so EV_RESULT = IV_VAL1 − IV_VAL2 (Planned Final Volume − Seed Volume).'),
  ('s','b. If a result exists and IV_TYPE2 is supplied, apply IV_TYPE2 to the result and IV_VAL3 '
   '(not used for Fill Volume).'),
  ('s','c. Division guards against a zero divisor (result set to 0).'),
  ('s','d. Call /SMPL/PPPI_FM_OUTPUT_VALUE to format EV_RESULT into EV_RESULT_OUT with the result UoM.'),
  ('h','Output'),
  ('b','EV_RESULT – numeric calculation result (the Fill Volume).'),
  ('b','EV_RESULT_OUT – the formatted result string (with UoM).'),
  ('h','Additional Notes'),
  ('h','Error Handling:'),
  ('b','No exceptions are defined; an invalid/zero divisor yields a result of 0.'),
  ('h','Dependencies:'),
  ('b','/SMPL/PPPI_FM_OUTPUT_VALUE for result formatting.'),
  ('h','Assumptions:'),
  ('b','Operation codes are valid; input values are already numeric floats (converted via /SMPL/PPPI_FM_INPUT_VALUE).'),
 ]}

# ---- AZ Phase 3 input-validation + goods-issue FMs (added 2026-07-14) ----
# Sourced: GET_MAT_DETAIL local .abap; GET_EXPIRY_DATE DE1_100 zsmpl_fg_az_phase2;
# CREATE_PROC_MSG DE1_100 zjc_fg_azp2 (the Z_PICONS goods-issue FM, movement type 261).
FMDATA['ZSMPL_FM_GET_MAT_DETAIL']={
 'name':'ZSMPL_FM_GET_MAT_DETAIL',
 'imports':[('IM_MATNR','MATNR','Material (part) number entered by the operator')],
 'exports':[('EX_MAT_DESC','MAKTX','Material description returned for the part number'),
            ('EX_UOM','MEINS','Base unit of measure of the material')],
 'exceptions':[('MAT_DESC_DNE_FOR_LANGU','No material description exists for the logon language'),
               ('UOM_NOT_FOUND','No base unit of measure found for the material')],
 'pseudo':[
   ('h','1. Purpose'),
   ('p','Retrieves the material description and base unit of measure for a material (part) number so the '
        'Material Description is populated automatically when the operator enters a Part No.'),
   ('h','2. Input Parameters'),
   ('b','IM_MATNR - the material (part) number entered by the operator.'),
   ('h','3. Processing Logic'),
   ('s','a. Move IM_MATNR to a working material variable.'),
   ('s','b. Select the material description (MAKTX) from table MAKT for the material in the logon language (SY-LANGU).'),
   ('s','c. If no description is found in the logon language, re-select MAKT for the material in English ("E").'),
   ('s','d. Select the base unit of measure (MEINS) from table MARA for the material.'),
   ('s','e. If no unit of measure is found, raise UOM_NOT_FOUND.'),
   ('s','f. Return the description in EX_MAT_DESC and the unit of measure in EX_UOM.'),
   ('h','Additional Notes'),
   ('h','Error Handling:'),
   ('b','MAT_DESC_DNE_FOR_LANGU - no material description exists for the material in the requested language.'),
   ('b','UOM_NOT_FOUND - the material has no base unit of measure in MARA.'),
   ('h','Dependencies:'),
   ('b','Material master tables MAKT (descriptions) and MARA (base data) must be maintained for the part.'),
   ('h','Assumptions:'),
   ('b','The part number entered corresponds to a material master record; English is available as a fallback language.'),
 ]}
FMDATA['ZSMPL_FM_GET_EXPIRY_DATE']={
 'name':'ZSMPL_FM_GET_EXPIRY_DATE',
 'imports':[('IM_MATNR','MATNR','Material (part) number of the supply (optional)'),
            ('IM_BATCH','CHARG_D','Batch number entered by the operator (optional)')],
 'exports':[('EX_EXP_DATE','VFDAT','Expiration (shelf-life) date returned for the material/batch')],
 'exceptions':[('MAT_IS_INITIAL','No material was supplied'),
               ('BATCH_COMBO_NOT_FOUND','The material/batch combination does not exist in SAP'),
               ('EXPIRY_DATE_IN_PAST','The batch expiration date is earlier than the current date')],
 'pseudo':[
   ('h','1. Purpose'),
   ('p','Validates the batch entered against the material and returns the batch expiration date so the Exp. Date '
        'is populated automatically when the operator enters a Batch No.'),
   ('h','2. Input Parameters'),
   ('b','IM_MATNR - the material (part) number of the supply.'),
   ('b','IM_BATCH - the batch number entered by the operator.'),
   ('h','3. Processing Logic'),
   ('s','a. If IM_MATNR is blank, raise MAT_IS_INITIAL.'),
   ('s','b. Select the expiration date (VFDAT) from batch table MCH1 for the material and batch.'),
   ('s','c. If the material/batch combination is not found, raise BATCH_COMBO_NOT_FOUND.'),
   ('s','d. If the expiration date is earlier than the current date (SY-DATLO), raise EXPIRY_DATE_IN_PAST.'),
   ('s','e. Return the expiration date in EX_EXP_DATE.'),
   ('h','Additional Notes'),
   ('h','Error Handling:'),
   ('b','MAT_IS_INITIAL - the material number was not supplied.'),
   ('b','BATCH_COMBO_NOT_FOUND - no MCH1 record exists for the material/batch combination.'),
   ('b','EXPIRY_DATE_IN_PAST - the batch expiration date has already passed.'),
   ('h','Dependencies:'),
   ('b','Batch master table MCH1 must hold the material/batch with a shelf-life expiration date (VFDAT).'),
   ('h','Assumptions:'),
   ('b','The part number has already been validated; batches are managed with shelf-life expiration in SAP.'),
 ]}
FMDATA['ZSMPL_FM_CREATE_PROC_MSG']={
 'name':'ZSMPL_FM_CREATE_PROC_MSG',
 'imports':[
   ('I_PLANT','WERKS_D','Plant for the goods issue'),
   ('I_DATE','DATE','Event date; defaults to the current date if blank (optional)'),
   ('I_TIME','TIMS','Event time; defaults to the current time if blank (optional)'),
   ('I_MATNR','MATNR','Material (part) number to be consumed'),
   ('I_GI_QTY','ERFMG','Goods-issue (consumed) quantity'),
   ('I_ORDER','AUFNR','Process order (optional)'),
   ('I_ERFME','MEINS','Unit of measure (optional)'),
   ('I_BWART','BWART','Movement type - 261 for order consumption (optional)'),
   ('I_RSNUM','RSNUM','Reservation number (optional)'),
   ('I_RSPOS','RSPOS','Reservation item (optional)'),
   ('I_MSG_HEAD','CO_SOURCE','Process-message sender name; defaults to the user (optional)'),
   ('I_BATCH','CHARG_D','Batch of the material (optional)'),
   ('I_PHASE','VORNR','Phase / operation number (optional)'),
   ('I_STLOC','LGORT_D','Storage location for the goods issue'),
   ('I_FLAG','CHAR1','Conditional trigger flag (optional)'),
   ('I_MATCH_FLAG','CHAR1','Value the trigger flag must match to proceed (optional)'),
 ],
 'exceptions':[('MESSAGE_CREATION_FAIL','The process message could not be created'),
               ('CHARACTERISTIC_ERROR','A process-message characteristic was rejected')],
 'pseudo':[
   ('h','1. Purpose'),
   ('p','Creates the custom goods-issue process message Z_PICONS to consume a material into SAP (movement type '
        '261, order consumption) when the operator signs a material line, replacing a manual SAP goods-issue '
        'transaction.'),
   ('h','2. Input Parameters'),
   ('b','I_PLANT / I_STLOC - plant and storage location for the goods issue.'),
   ('b','I_MATNR / I_BATCH / I_GI_QTY / I_ERFME - the material, batch, consumed quantity and unit of measure.'),
   ('b','I_ORDER / I_PHASE / I_RSNUM / I_RSPOS - process order, phase and reservation reference.'),
   ('b','I_BWART - movement type (261 for order consumption).'),
   ('b','I_DATE / I_TIME - event date and time (default to the system date/time).'),
   ('b','I_FLAG / I_MATCH_FLAG - optional conditional trigger.'),
   ('h','3. Processing Logic'),
   ('s','a. If I_FLAG is set and does not equal I_MATCH_FLAG, return without creating a message.'),
   ('s','b. Condense and upper-case the material and batch; if either is "N/A"/"NA", or the material is blank, '
        'return without creating a message.'),
   ('s','c. Default the event date and time to the system date/time when not supplied.'),
   ('s','d. Build the process-message header for category Z_PICONS (plant and sender name).'),
   ('s','e. Build the characteristics: event date/time, material, quantity consumed, process order, unit of '
        'measure, movement type, reservation and item, batch, phase and storage location.'),
   ('s','f. Call BAPI_PROCESS_MESSAGE_CREATEMLT to create the message.'),
   ('s','g. Inspect the header, characteristic and general return tables; raise CHARACTERISTIC_ERROR or '
        'MESSAGE_CREATION_FAIL on any error message.'),
   ('h','Additional Notes'),
   ('h','Error Handling:'),
   ('b','CHARACTERISTIC_ERROR - a characteristic value was rejected by the process-message BAPI.'),
   ('b','MESSAGE_CREATION_FAIL - the header or general return contained an error message.'),
   ('b','Materials/batches of "N/A" and blank materials are skipped silently (no message and no error).'),
   ('h','Dependencies:'),
   ('b','Process message category Z_PICONS and the standard BAPI_PROCESS_MESSAGE_CREATEMLT; the message is '
       'posted by the process-message destination that executes the movement.'),
   ('h','Assumptions:'),
   ('b','The plant, storage location and movement type are configured for order consumption; the material and '
       'batch have been validated on the line before signing.'),
 ]}
